### ISSUE TITLE
rivine explorer dumps all info -> redis server

### ISSUE THREAD

**Issue by despiegk** [rivine/home#4]
these specs are prob double & need to go elsewhere, but need something to organize our thoughts.

```toml
address = 
tokens_amount = 
locked_up_till = epoch
multisign = [[address,state],...] # state is bool
```

address means wallet address
